apiVersion: v1
kind: Service
metadata:
  name: devsync-service
spec:
  selector:
    app: devsync
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
  type: NodePort
